import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="w-full bg-gray-900 text-gray-400 text-xs py-4 px-4 text-center mt-auto">
          <div className="max-w-4xl mx-auto space-y-1">
            <p>상호명: 이너몰 | 사업자등록번호: 685-26-02075</p>
            <p>대표자명: 인찬혁 | 사업장 주소: 경기도 고양시 덕양구 지도로 124번길 46-15, 702호</p>
            <p>전화번호: 010-8470-9878</p>
            <p className="mt-2">
              <a href="/policy" className="text-yellow-400 hover:underline">서비스 이용약관 및 환불 규정</a>
            </p>
            <p className="text-gray-500 mt-2">© 2026 이너몰. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
